# Stage 1: Build the base image with Python installed
FROM python:3.12.2-alpine3.19 as base

# Install system dependencies
RUN apk add --no-cache gcc musl-dev tzdata
RUN pip install --upgrade pip

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /code/fastapis

# Stage 2: Install Python dependencies
FROM base AS builder

# Copy requirements file
COPY requirements.txt .

# Use pip wheel to build dependencies
RUN pip install --upgrade pip \
    && pip wheel --no-cache-dir --no-deps --wheel-dir /wheels -r requirements.txt

# Stage 3: Copy the application code and install dependencies
FROM base AS runtime

ENV TZ=America/Los_Angeles

# Copy pre-built wheels from builder stage
COPY --from=builder /wheels /wheels
COPY --from=builder /code/fastapis/requirements.txt .

# Install the dependencies
RUN pip install --no-cache /wheels/*

# Copy the application code to the container
COPY . .
COPY ./.env .

RUN chmod 777 /crmdir/uploads/fast/log
RUN chmod 777 /crmdir/uploads/fast/files

# Expose the port the app runs on
EXPOSE 8000

# Command to run the FastAPI app using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
