version: '3.8'

services:
  redis:
    image: redis:7.2.4-alpine
    container_name: redis_c
    ports:
      - "6379:6379"
    hostname: srv.redis
    volumes:
      - ./redis_data:/data
    networks:
      web:
        ipv4_address: 10.5.0.4
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: always
    command: redis-server --save 900 1 --save 300 10 --save 60 10000 --rdbcompression yes --dbfilename dump.rdb --appendonly yes --appendfilename "appendonly.aof" --appendfsync everysec

networks:
  web:
    name: simple_web
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1