FROM node:21.7.1-alpine3.18

RUN apk update
RUN apk add --no-cache tzdata

ENV TZ=America/Los_Angeles

WORKDIR /code/dashboard

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

COPY . .

EXPOSE 3000
CMD ["npm", "run", "dev"]
