FROM node:21.7.1-alpine3.18

RUN apk update
RUN apk add --no-cache tzdata
#RUN apt update
#RUN apt install tzdata

ENV TZ=America/Los_Angeles

WORKDIR /code/api/run

# Copy package.json and package-lock.json
COPY ./run/package*.json ./

# Install dependencies
RUN npm install

COPY ./run .

EXPOSE 3000
CMD ["npm", "run", "dev"]
