version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13.0-rc.4-management
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    hostname: srv.rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data
    labels:
      NAME: "rabbitmq1"
    networks:
      web:
        ipv4_address: 10.5.0.20

networks:
  web:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1