version: '3.8'
services:
  messaging:
    image: pytap_i
    container_name: pytap_c
    build:
      context: ./pytap/src
      dockerfile: ../../Dockerfile.pytap.PRD
      args: 
        env: prd
    restart: always
    hostname: srv.pytap
    ports:
      - 8001:8000
      - 8889:8888
      - 5679:5678
      - 4000:80
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./uploads/pytap/log:/crmdir/uploads/pytap/log
    networks:
      web:
        ipv4_address: 10.5.0.2

networks:
  web:
    name: simple_web
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1