version: '3.8'

include:
  - docker-compose-pytap-PRD.yaml
  - docker-compose-sock-PRD.yaml
  #- docker-compose-rabbitmq.yaml
  - docker-compose-fastapi-PRD.yaml
  - docker-compose-dashboard-PRD.yaml
  - docker-compose-api-PRD.yaml
  - docker-compose-couchdb.yaml
  - docker-compose-redis.yaml

networks:
  web:
    name: simple_web
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1