version: '3.8'

services:
  couchserver:
    build:
      context: ./couchdb
      dockerfile: ../Dockerfile.couchdb
    restart: always
    container_name: syscouchdb
    hostname: srv.syscouchdb
    ports:
      - "6984:5984"
    environment:
      - COUCHDB_USER=dashboard
      - "COUCHDB_PASSWORD=Jimena1000$"
      - COUCHDB_URL=http://localhost:6984
      - COUCHDB_DB=sinpe
      - TZ=America/Los_Angeles
    volumes:
        - ./couchdb/dbdata:/opt/couchdb/data
    networks:
      web:
        ipv4_address: 10.5.0.5

networks:
  web:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1