version: '3.8'
services:
  websocking:
    image: sock_i
    container_name: sock_c
    build:
      context: ./sock/src
      dockerfile: ../../Dockerfile.sock.dev
      args: 
        env: dev
    restart: always
    hostname: srv.sock
    ports:
      - 7789:6789
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./sock/src:/code/sock
      - ./uploads/sock/log:/opt/uploads/sock/log
    networks:
      web:
        ipv4_address: 10.5.0.7

networks:
  web:
    name: simple_web
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1